#!/bin/sh

IPSETS_RESTORE="/etc/ipsets.restore"
IPTABLES_RESTORE="/etc/iptables.restore"
IP6TABLES_RESTORE="/etc/ip6tables.restore"


if [ -f ${IPSETS_RESTORE} ]; then
    ipset restore < "${IPSETS_RESTORE}"
fi

if [ -f ${IPTABLES_RESTORE} ]; then
    iptables-restore < "${IPTABLES_RESTORE}"
fi

if [ -f ${IP6TABLES_RESTORE} ]; then
    ip6tables-restore < "${IP6TABLES_RESTORE}"
fi
